spring.application.name=telecom_system
# PostgreSQL 配置
spring.datasource.url=jdbc:postgresql://localhost:5432/telecom_system
spring.datasource.username=postgres
spring.datasource.password=123456


# JPA 配置
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# 开发配置
spring.thymeleaf.cache=false
server.port=8080
logging.level.com.telecom=DEBUG


# Redis 配置
spring.data.redis.host=localhost
spring.data.redis.port=6379
# spring.data.redis.password=password  # 如果Redis有密码，需要设置
spring.data.redis.database=0
spring.data.redis.timeout=2000ms

# 缓存配置
spring.cache.type=redis
spring.cache.redis.time-to-live=3600000

# 开发配置
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
